mensaje = "¡Hola mundo Python!"
print(mesaje)

# Produce el siguiente error:
# Traceback (most recent call last):
#  File "b3-hola_mundo_con_eror.py", line 2, in <module>
#     print(mesaje)
# NameError: name 'mesaje' is not defined

# El error se encuentra en la línea 2 y es que 'mesaje' no está definido.
